### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by benebsiny** [suren-atoyan/monaco-react#106]
**Describe the bug**
I followed the code at [README](https://github.com/suren-atoyan/monaco-react#monaco-instance) to instance monacro. And it shows the error message.

P.S. I'm using next.js

**To Reproduce**
1. paste the following code at pages/editor.js
```javascript
import {monaco} from "@monaco-editor/react";

export default () => {
  monaco
    .init()
    .then(monaco => {
      console.log(monaco)
    })
  return <Editor height="100%" language="javascript"/>;
}
```
2. Open http://localhost:3000/editor
3. Show the following message at console
```
ReferenceError: window is not defined
    at Object.init (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\@monaco-editor\react\lib\utils\monaco.js:53:5)
    at module.exports../components/Editor/Editor.js.__webpack_exports__.default (C:\Users\benebsiny\Desktop\bdd-for-web-test\.next\server\pages\editor.js:135:63)
    at processChild (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at Object.renderPage (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\next\dist\next-server\server\render.js:45:686)
    at Function.getInitialProps (C:\Users\benebsiny\Desktop\bdd-for-web-test\.next\server\pages\_document.js:276:19)
    at loadGetInitialProps (C:\Users\benebsiny\Desktop\bdd-for-web-test\node_modules\next\dist\next-server\lib\utils.js:5:101)
event - build page: /next/dist/pages/_error
```

**Expected behavior**
Show the editor in the page instead of error message.

**Screenshots**
![](https://imgur.com/mroJiGL.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 3.5.7

**Additional context**
I'm using next.js

**Comment by suren-atoyan** [comment]
Hello @benebsiny.

`Nex.js` tries to do server-side rendering, but the library works only in the browser. I don't know `Next.js` details much, but I saw [this solution](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) used by devs with `next.js`.

Please let me know if it works, I guess I should add a section in the README for `Next.js` users.

**Comment by benebsiny** [comment]
I found an easy way to solve this, just add `if (typeof window !== "undefined")` and the problem solved.
Examples:
```javascript
import Editor, {monaco} from "@monaco-editor/react";

export default () => {
  if (typeof window !== "undefined") {
    monaco
      .init()
      .then(monaco => {
        console.log(monaco);
      });
  }
  return <Editor height="100%" language="javascript"/>;
}
```

**Comment by suren-atoyan** [comment]
So, definitely it will solve your problem, the question is how much it is acceptable for `next.js` community 😄 I think there should be a better solution; for me, it doesn't look great. But anyway from my side I'll create a new section in the documentation about possible cases in `next.js`.

Thank you for your support.
