### ISSUE TITLE
Installing leads to `TypeError: babel__default.default.default is not a function`

### ISSUE THREAD

**Issue by not-a-bobbit-fish** [suren-atoyan/monaco-react#214]
**Describe the bug**

When trying to do a `yarn install` or `npm install`, I got this:

```
> @monaco-editor/react@4.1.0 lint /Users/philippeterson/Code/monaco-react
> npx eslint src


> @monaco-editor/react@4.1.0 build /Users/philippeterson/Code/monaco-react
> rollup -c && cp ./src/types.d.ts ./lib/

[!] TypeError: babel__default.default.default is not a function
TypeError: babel__default.default.default is not a function
    at Object.<anonymous> (/Users/philippeterson/Code/monaco-react/rollup.config.mjs:23:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.require.extensions.(anonymous function) [as .mjs] (/Users/philippeterson/Code/monaco-react/node_modules/rollup/dist/shared/loadConfigFile.js:513:20)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadConfigFromBundledFile (/Users/philippeterson/Code/monaco-react/node_modules/rollup/dist/shared/loadConfigFile.js:521:42)
    at getDefaultFromTranspiledConfigFile (/Users/philippeterson/Code/monaco-react/node_modules/rollup/dist/shared/loadConfigFile.js:505:12)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @monaco-editor/react@4.1.0 build: `rollup -c && cp ./src/types.d.ts ./lib/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @monaco-editor/react@4.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philippeterson/.npm/_logs/2021-03-27T02_29_09_906Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @monaco-editor/react@4.1.0 prepublish: `npm test && npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @monaco-editor/react@4.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philippeterson/.npm/_logs/2021-03-27T02_29_10_132Z-debug.log
```

**Solution**

I realized it might be a node version issue. I was using v10.18.1 and just upgraded to latest and it worked.

**Comment by not-a-bobbit-fish** [comment]
Closing because I solved this issue.
