### ISSUE TITLE
Use monaco-editor as a local package, but a worker-related error occurs

### ISSUE THREAD

**Issue by Sky-FE** [suren-atoyan/monaco-react#408]
**Describe the bug**
I refer to the usage method in the documentation and use monaco-editor as a local package. The following is the sample code:
```ts
import * as monaco from 'monaco-editor';
import MonacoEditor, {  loader } from '@monaco-editor/react';

loader.config({
  monaco,
});
```

But after using it in my project, it produces the following error:
```shell
Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:1)
    at webWorker.js:38:1
```

**Screenshots**
<img width="633" alt="image" src="https://user-images.githubusercontent.com/23622592/192154966-8c647667-2dce-4cd9-93df-8009ce7be287.png">

**Desktop**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [105.0.5195.102]

**Additional context**
- @monaco-editor/react@4.4.5
- monaco-editor@0.33.0
- Created by CRA eject mode

Is there any good way to solve the above problem?

**Comment by suren-atoyan** [comment]
With `CRA` you need to use an additional [webpack-plugin](https://www.npmjs.com/package/monaco-editor-webpack-plugin).

With `Vite`, you can do the following:

```js
import { loader } from "@monaco-editor/react";

import * as monaco from "monaco-editor";
import editorWorker from "monaco-editor/esm/vs/editor/editor.worker?worker"
import jsonWorker from "monaco-editor/esm/vs/language/json/json.worker?worker"
import cssWorker from "monaco-editor/esm/vs/language/css/css.worker?worker"
import htmlWorker from "monaco-editor/esm/vs/language/html/html.worker?worker"
import tsWorker from "monaco-editor/esm/vs/language/typescript/ts.worker?worker"

self.MonacoEnvironment = {
  getWorker(_, label) {
    if (label === "json") {
      return new jsonWorker()
    }
    if (label === "css" || label === "scss" || label === "less") {
      return new cssWorker()
    }
    if (label === "html" || label === "handlebars" || label === "razor") {
      return new htmlWorker()
    }
    if (label === "typescript" || label === "javascript") {
      return new tsWorker()
    }
    return new editorWorker()
  }
}

loader.config({ monaco });

loader.init().then(/* ... */);
```

**Comment by alolonghun** [comment]
@suren-atoyan Yes, i have used `monaco-editor-webpack-plugin`, but still getting the same error.

**Comment by austzyl** [comment]
I had the  same error in my react project.

"@monaco-editor/react": "^4.4.6",
"react": "^16.8.6",

import * as monaco from "monaco-editor";
import Editor, { loader } from "@monaco-editor/react";
loader.config({ monaco });
![image](https://user-images.githubusercontent.com/11569358/202908921-04f01e38-a547-4c20-8291-23b6869999a5.png)

**Comment by Business99** [comment]
Same error here. Works perfectly, however it just spams my console with these errors.

```javascript
import * as monaco from "monaco-editor"
import Editor, {loader} from "@monaco-editor/react";

loader.config({monaco});

function App() {
  return (
    <div className="App">
      <Editor height={"90vh"} defaultLanguage={"javascript"} defaultValue={"const bubble = () => {console.log('yeet')}"}/>
    </div>
  );
}

export default App;
```
![image](https://user-images.githubusercontent.com/111577365/204302539-0e143001-3136-4c41-9563-e054eced3108.png)

**Comment by suren-atoyan** [comment]
@jakajancar I've never tested it with plain `esbuild`, do you get errors with `esbuild`?

**Comment by RobertCLian** [comment]
@Business99 have u found way to fix the error? I got the same issues

**Comment by vladtimss** [comment]
Hi all,
have the same error. Did you solved it?

**Comment by NoManPlay** [comment]
I resolved this error  in `esbuild` 
```typescript
(window as any).MonacoEnvironment = {
  getWorker: (workerId: string, label: string) => {
    if (label === 'json') {
      return new Worker(
        new URL('monaco-editor/esm/vs/language/json/json.worker?worker', import.meta.url),
      );
    }
    return new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker?worker', import.meta.url));
  },
};
```

**Comment by hljwwyy123** [comment]
using  
"@monaco-editor/react": "^4.5.1"
"monaco-editor": "^0.40.0"
this conf work!

import * as monaco from "monaco-editor"
import jsonworker from "monaco-editor/esm/vs/language/json/json.worker.js"
import editorWorker from "monaco-editor/esm/vs/editor/editor.worker.js"

...

(window as any).MonacoEnvironment = {
  getWorkerUrl: (workerId: string, label: string) => {
    if (label === 'json') {
      return new jsonworker()
    }
    return new editorWorker()
  },
};

loader.config({ monaco });

<Editor 
  language={'json'}
/>

**Comment by GuanJdoJ** [comment]
same +1

<img width="560" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/30386473/1667efc6-39fd-4513-a02e-698eb3ed2ccf">
