### ISSUE TITLE
Load monaco files from node_modules doesn't work

### ISSUE THREAD

**Issue by vladtimss** [suren-atoyan/monaco-react#482]
Hi! Thanks for your great job of this project.

I extremely need help to solve problem with load monaco from node modules.

Below you can see my usage of @monaco-editor/react via loader. My problem is not understanding how set correct paths a vs in loader.config({ paths: { vs: **_HERE_** } }). Please help to understand what's wrong from my side. 

I tried to read carefully this [discussion](https://github.com/suren-atoyan/monaco-react/issues/12). But, `import { monaco } from '@monaco-editor/react';` than monaco doesn't have method as config, urls etc. We only now can use loader.config.

if a set path by node_modules, than get `SyntaxError: Unexpected token '<' (at loader.js:1:1)`

Please help!

```
import React, { useLayoutEffect, useRef } from 'react';
import { loader } from '@monaco-editor/react';

const MonacoEditorWrapper = () => {
    const monacoRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        loader.config({
            paths: {
                // vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs', - **if i use this - it will be work correctly of course but i do not understand how replace cdn on node_modules load**
                vs: 'node_modules/monaco-editor/min-maps/vs',
            },
            'vs/nls': {
                availableLanguages: {
                    '*': 'de',
                },
            },
        });

        loader.init().then((monaco) => {
            if (!monacoRef.current) {
                return;
            }
            monacoRef.current.style.height = '100vh';
            const properties = {
                value: 'function hello() {\n\talert(\'Hello world!\');\n}',
                language: 'javascript',
            };
            monaco.editor.create(monacoRef.current, properties);
        });
    }, []);

    return <div ref={monacoRef} />;
};

export { MonacoEditorWrapper };

```

**Comment by vladtimss** [comment]
> @vladtimss try [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)

but if i use CRA, a don't understand how can add webpack plugin

**Comment by suren-atoyan** [comment]
@vladtimss do the following:

1. copy all of `monaco-editor` files into repo's `/public` directory

```bash
cp -R ./node_modules/monaco-editor/min/vs ./public
```

2. configure your loader

```js
import { loader } from '@monaco-editor/react';

loader.config({ paths: { vs: '/vs' } });
```

**Comment by dmagunov** [comment]
I've made some research on this topic and have shared my findings in an [article](https://github.com/dmagunov/snapshots.lol/wiki/Collaborative-editing-with-Yjs-and-Monaco-editor-in-Next.js-application#solution-2-load-monaco-editor-from-node_modules). Hopefully, it will be useful.

**Comment by Kaltsit163** [comment]
> Hi! Thanks for your great job of this project.
> 
> I extremely need help to solve problem with load monaco from node modules.
> 
> Below you can see my usage of @monaco-editor/react via loader. My problem is not understanding how set correct paths a vs in loader.config({ paths: { vs: **_HERE_** } }). Please help to understand what's wrong from my side.
> 
> I tried to read carefully this [discussion](https://github.com/suren-atoyan/monaco-react/issues/12). But, `import { monaco } from '@monaco-editor/react';` than monaco doesn't have method as config, urls etc. We only now can use loader.config.
> 
> if a set path by node_modules, than get `SyntaxError: Unexpected token '<' (at loader.js:1:1)`
> 
> Please help!
> 
> ```
> import React, { useLayoutEffect, useRef } from 'react';
> import { loader } from '@monaco-editor/react';
> 
> const MonacoEditorWrapper = () => {
>     const monacoRef = useRef<HTMLDivElement>(null);
> 
>     useEffect(() => {
>         loader.config({
>             paths: {
>                 // vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs', - **if i use this - it will be work correctly of course but i do not understand how replace cdn on node_modules load**
>                 vs: 'node_modules/monaco-editor/min-maps/vs',
>             },
>             'vs/nls': {
>                 availableLanguages: {
>                     '*': 'de',
>                 },
>             },
>         });
> 
>         loader.init().then((monaco) => {
>             if (!monacoRef.current) {
>                 return;
>             }
>             monacoRef.current.style.height = '100vh';
>             const properties = {
>                 value: 'function hello() {\n\talert(\'Hello world!\');\n}',
>                 language: 'javascript',
>             };
>             monaco.editor.create(monacoRef.current, properties);
>         });
>     }, []);
> 
>     return <div ref={monacoRef} />;
> };
> 
> export { MonacoEditorWrapper };
> ```

### I gave up on load resouce from node_modules and chose the CDN address
Recently I encountered a similar problem. I searched on Google for `a long time` and tried many solutions. However, I found that `loading monaco-editor from the local node_modules directory using a Loader does not work`,I gave up on this method and chose to switch to a different CDN address to solve the slow loading problem.

### ❌ Writing like this will cause the loss of the highlighting
```javascript
import Editor from "@monaco-editor/react";
import loader from '@monaco-editor/loader';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
loader.config({ monaco });
```

### ❌ Writing like this will cause some errors
```javascript
import Editor from "@monaco-editor/react";
import loader from '@monaco-editor/loader';
import * as monaco from 'monaco-editor';
loader.config({ monaco });
```
<img width="527" alt="image" src="https://github.com/suren-atoyan/monaco-react/assets/17058691/f7711db8-3c58-4c89-8681-51a98240b61e">


### ✅ At last I have found a solution here. If you are a user in mainland China :
```javascript
import Editor from "@monaco-editor/react";
import loader from '@monaco-editor/loader';
loader.config({ paths: { vs: 'https://g.alicdn.com/code/lib/monaco-editor/0.44.0/min/vs' } });
```
This is the CDN address provided by Alibaba, which has a great speed in mainland China.
