### ISSUE TITLE
Cannot add suggestions to custom language

### ISSUE THREAD

**Issue by miszal** [suren-atoyan/monaco-react#501]
**Describe the bug**
Adding custom suggestions via `registerCompletionItemProvider` does nothing. Moreover previous suggestions ( previously added texts) disappeared.

**To Reproduce**
```
    monaco?.languages.registerCompletionItemProvider('customLang', {
      provideCompletionItems: () => {
        return {
          suggestions: [
            {
              label: 'Suggestion 1',
              kind: monaco.languages.CompletionItemKind.Keyword,
              insertText: 'suggestion1',
              range: {
                startLineNumber: 0,
                startColumn: 0,
                endLineNumber: 0,
                endColumn: 0,
              },
            },
          ],
        };
      },
    });
```

**Expected behavior**
Suggestion will be added and shown in dropdown.

**Screenshots**
![image](https://github.com/suren-atoyan/monaco-react/assets/9151989/ce6c2ac5-6e4f-46f4-9ce4-76c3ef432143)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome 
 - Version 114.0.5735.134

**Comment by voigtito** [comment]
Try setting the right range for it, something like this:

```
monaco?.languages.registerCompletionItemProvider('customLang', {
      provideCompletionItems: (model, position) => {
      
        const range = new monaco.Range(
            position.lineNumber,
            1,
            position.lineNumber,
            position.column
        );
        
        return {
          suggestions: [
            {
              label: 'Suggestion 1',
              kind: monaco.languages.CompletionItemKind.Keyword,
              insertText: 'suggestion1',
              range
            },
          ],
        };
      },
    });
```

**Comment by suren-atoyan** [comment]
@miszal let me know if @voigtito suggestion helps?

**Comment by miszal** [comment]
Ok. I set range wrong.
This solution works for me:
`      const word = model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };`

**Comment by voigtito** [comment]
@suren-atoyan is the method `registerInlineCompletionsProvider` supported?

I am trying this example to create a ghost text suggestion, just like github copilot but for a custom language:

```
monaco.languages.registerInlineCompletionsProvider('custom', {
        provideInlineCompletions(model, position, context, token) {
          console.log(model, position, context, token);
          const completion = [
            {
              range: new monaco.Range(position.lineNumber, 1, position.lineNumber, 10),
              text: 'Hello World',
            },
            {
              range: new monaco.Range(position.lineNumber, 1, position.lineNumber, 10),
              text: 'Hello World2',
            },
          ];
          return { items: completion };
        },
      });
```

**Comment by voigtito** [comment]
I am getting this error on the console when trying to use the code provided before:

```
errors.ts:26 Uncaught Error: Cannot use 'in' operator to search for 'snippet' in undefined

TypeError: Cannot use 'in' operator to search for 'snippet' in undefined
    at inlineCompletionsModel.ts:819:15
    at Generator.next (<anonymous>)
    at S (css.ts:81:1)
    at errors.ts:26:12
```

**Comment by voigtito** [comment]
Already solved it! I was checking the wrong part of the documentation. Here is the full code if anyone needs:

```
monaco.languages.registerInlineCompletionsProvider('custom', {
        provideInlineCompletions(model, position, context, token) {
          console.log(model, position, context, token);
          const completion = [
            {
              range: new monaco.Range(position.lineNumber, 1, position.lineNumber, 10),
              insertText: { snippet: 'Hello World' },
            },
            {
              range: new monaco.Range(position.lineNumber, 1, position.lineNumber, 10),
              insertText: { snippet: 'Hello World2' },
            },
          ];
          return { items: completion };
        },
      });
```
