### ISSUE TITLE
How should I integrate Monaco SQL Language?

### ISSUE THREAD

**Issue by resetsix** [suren-atoyan/monaco-react#599]
**Is your feature request related to a problem? Please describe.**

- I'm using [CRA](https://github.com/facebook/create-react-app) to create a project, and I'm using [craco](https://github.com/dilanx/craco) to extend CRA's `webpack` configuration. Since `monaco-react` doesn't require any webpack configuration, I'm not sure how I should use a custom language.

**Describe the solution you'd like**

- I would like to integrate [Monaco SQL Language](https://github.com/DTStack/monaco-sql-languages) in `monaco-react` for big data SQL language keyword hints!

**Describe alternatives you've considered**

- I was able to integrate `Monaco SQL Language` correctly in [react-monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor), using the figured out `craco.config.js` configuration, but monaco-react fails.

**Additional context**

- The following is the effect of successfully integrating `Monaco SQL Language` with r`eact-monaco-editor` configuration code.

<img width="583" alt="图片" src="https://github.com/suren-atoyan/monaco-react/assets/85431995/9aa0c3ab-db5d-4b3f-b345-d713bf809c1c">

// App.tsx
```tsx
import MonacoEditor from "react-monaco-editor";

function App() {
    return <MonacoEditor height={600} language="mysql" theme="vs-dark" />;
}

export default App;
```

// craco.config.js
```js
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const webpack = require("webpack");
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const process = require("process");

const monacoWebpackPlugin = new MonacoWebpackPlugin({
    // features: [],
    // languages: [],
    customLanguages: [
        {
            label: "mysql",
            entry: "monaco-sql-languages/out/esm/mysql/mysql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/mysql/mySQLWorker",
                entry: "monaco-sql-languages/out/esm/mysql/mysql.worker",
            },
        },
        {
            label: "flinksql",
            entry: "monaco-sql-languages/out/esm/flinksql/flinksql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/flinksql/flinkSQLWorker",
                entry: "monaco-sql-languages/out/esm/flinksql/flinksql.worker",
            },
        },
        {
            label: "sparksql",
            entry: "monaco-sql-languages/out/esm/sparksql/sparksql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/sparksql/sparkSQLWorker",
                entry: "monaco-sql-languages/out/esm/sparksql/sparksql.worker",
            },
        },
        {
            label: "hivesql",
            entry: "monaco-sql-languages/out/esm/hivesql/hivesql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/hivesql/hiveSQLWorker",
                entry: "monaco-sql-languages/out/esm/hivesql/hivesql.worker",
            },
        },
        {
            label: "trinosql",
            entry: "monaco-sql-languages/out/esm/trinosql/trinosql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/trinosql/TrinoSQLWorker",
                entry: "monaco-sql-languages/out/esm/trinosql/trinosql.worker",
            },
        },
        {
            label: "pgsql",
            entry: "monaco-sql-languages/out/esm/pgsql/pgsql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/pgsql/PgSQLWorker",
                entry: "monaco-sql-languages/out/esm/pgsql/pgsql.worker",
            },
        },
        {
            label: "impalasql",
            entry: "monaco-sql-languages/out/esm/impalasql/impalasql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/impalasql/impalaSQLWorker",
                entry: "monaco-sql-languages/out/esm/impalasql/impalasql.worker",
            },
        },
    ],
});

// eslint-disable-next-line no-undef
module.exports = {
    webpack: {
        plugins: [
            new webpack.DefinePlugin({
                "process.env.NODE_DEBUG": process.env.NODE_DEBUG,
            }),
            monacoWebpackPlugin,
        ],
    },
};

```

- Below is the configuration code and effect of a failed `Monaco SQL Language` integration using `monaco-react`.

<img width="586" alt="图片" src="https://github.com/suren-atoyan/monaco-react/assets/85431995/10206b77-358f-4a59-91aa-3c5aa747a605">

// App.tsx
```tsx
import Editor from "@monaco-editor/react";

function App() {
    return <Editor height={600} language="mysql" theme="vs-dark" />;
}

export default App;
```

// craco.config.js
```js
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const webpack = require("webpack");
// eslint-disable-next-line @typescript-eslint/no-var-requires, no-undef
const process = require("process");

const monacoWebpackPlugin = new MonacoWebpackPlugin({
    // features: [],
    // languages: [],
    customLanguages: [
        {
            label: "mysql",
            entry: "monaco-sql-languages/out/esm/mysql/mysql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/mysql/mySQLWorker",
                entry: "monaco-sql-languages/out/esm/mysql/mysql.worker",
            },
        },
        {
            label: "flinksql",
            entry: "monaco-sql-languages/out/esm/flinksql/flinksql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/flinksql/flinkSQLWorker",
                entry: "monaco-sql-languages/out/esm/flinksql/flinksql.worker",
            },
        },
        {
            label: "sparksql",
            entry: "monaco-sql-languages/out/esm/sparksql/sparksql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/sparksql/sparkSQLWorker",
                entry: "monaco-sql-languages/out/esm/sparksql/sparksql.worker",
            },
        },
        {
            label: "hivesql",
            entry: "monaco-sql-languages/out/esm/hivesql/hivesql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/hivesql/hiveSQLWorker",
                entry: "monaco-sql-languages/out/esm/hivesql/hivesql.worker",
            },
        },
        {
            label: "trinosql",
            entry: "monaco-sql-languages/out/esm/trinosql/trinosql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/trinosql/TrinoSQLWorker",
                entry: "monaco-sql-languages/out/esm/trinosql/trinosql.worker",
            },
        },
        {
            label: "pgsql",
            entry: "monaco-sql-languages/out/esm/pgsql/pgsql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/pgsql/PgSQLWorker",
                entry: "monaco-sql-languages/out/esm/pgsql/pgsql.worker",
            },
        },
        {
            label: "impalasql",
            entry: "monaco-sql-languages/out/esm/impalasql/impalasql.contribution",
            worker: {
                id: "monaco-sql-languages/out/esm/impalasql/impalaSQLWorker",
                entry: "monaco-sql-languages/out/esm/impalasql/impalasql.worker",
            },
        },
    ],
});

// eslint-disable-next-line no-undef
module.exports = {
    webpack: {
        plugins: [
            new webpack.DefinePlugin({
                "process.env.NODE_DEBUG": process.env.NODE_DEBUG,
            }),
            monacoWebpackPlugin,
        ],
    },
};
```

**Comment by suren-atoyan** [comment]
@resetsix you should [use monaco-editor as an npm package](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#use-monaco-editor-as-an-npm-package)

**Comment by resetsix** [comment]
> @resetsix you should [use monaco-editor as an npm package](https://github.com/suren-atoyan/monaco-react?tab=readme-ov-file#use-monaco-editor-as-an-npm-package)

Thank you very much for your reply!

I added the following code snippet to fix this non-functioning issue

```tsx
import * as monaco from "monaco-editor/esm/vs/editor/editor.api";
loader.config({ monaco });
```

Both [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react) and [monaco-editor](https://github.com/microsoft/monaco-editor) need to be installed.

```bash
yarn add monaco-edtior @monaco-editor/react
```

**Comment by suren-atoyan** [comment]
@resetsix you are welcome 🙌

The issue is fixed, right? If so feel free to close it!

**Comment by resetsix** [comment]
> @resetsix you are welcome 🙌
> 
> The issue is fixed, right? If so feel free to close it!

OK

**Comment by destinyzwz** [comment]
> > @resetsix别客气🙌
> > 问题已经解决了，对吧？如果是的话，请随时关闭它！
> 
> 好的

Hello, can you show the complete code configuration and version? My relevant information is as follows, but there is an error, and there is no auto-complete suggestion。

"@monaco-editor/react": "^4.4.6",
"monaco-editor": "^0.31.1",
"monaco-editor-webpack-plugin": "^6.0.0",
"monaco-sql-languages": "^0.9.5",


![20250112170703](https://github.com/user-attachments/assets/cf1265b2-9767-46f3-856e-ab11fdfc0454)
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:460:1)
    at webWorker.js:38:1

**Comment by resetsix** [comment]
@destinyzwz you can try this

https://github.com/resetsix/react-monaco-sql-language-demo/issues/1#issuecomment-2178101800

**Comment by destinyzwz** [comment]
> @destinyzwz you can try this
> 
> [resetsix/react-monaco-sql-language-demo#1 (comment)](https://github.com/resetsix/react-monaco-sql-language-demo/issues/1#issuecomment-2178101800)

Thank you, but I had to use some older versions of the package in my old project
