### ISSUE TITLE
Uncaught TypeError: t.getModifierState is not a function 

### ISSUE THREAD

**Issue by swetapatnaik** [suren-atoyan/monaco-react#608]
**Describe the bug**

Uncaught TypeError: e.getModifierState is not a function when using AutoFill in Chrome or Edge

**To Reproduce**

Using Chrome or Edge
Enter some text in the text box "Use AutoFill to populate this textbox"
Click Reload to populate your auto fill buffer in the browser
Now click inside the text box "Use AutoFill to populate this textbox"
Choose your text from the "Saved data" dropdown

In the console following error is thrown.
Uncaught TypeError: e.getModifierState is not a function
    at new StandardKeyboardEvent (keyboardEvent.ts:111:24)
    at HTMLBodyElement.<anonymous> (dom.ts:178:18)

Or, please add a minimal code snippet to reproduce the issue, for example in [codesandbox](https://codesandbox.io/).

**Expected behavior**
No error to be thrown 

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome, Edge

**Additional context**

**Comment by ryuujo1573** [comment]
This is fixed per microsoft/monaco-editor#4325.
