### ISSUE TITLE
Uncaught Error: TextModel got disposed before DiffEditorWidget model got reset

### ISSUE THREAD

**Issue by armisael** [suren-atoyan/monaco-react#647]
When using `DiffEditor` with Monaco 0.51 and the component is unmounted, the following error is thrown:

```
Error: TextModel got disposed before DiffEditorWidget model got reset
    at u.value (diffEditorWidget.ts:327:24)
    at d._deliver (event.ts:1213:13)
    at d._deliverQueue (event.ts:1224:9)
    at d.fire (event.ts:1248:9)
    at q.dispose (textModel.ts:356:23)
...
```

The error does not appear with Monaco 0.50.

**To Reproduce**

I prepared a minimal code snippet to reproduce the issue: https://github.com/armisael/test-react-monaco-diff

Simply:
1. `npm run dev`
2. open your browser on http://localhost:3000
3. open the inspector
4. click on "Show editor"
5. click on "Hide editor"
6. see the error in console

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Arc (chromium-based)
 - Version: @monaco-editor/react 4.6.0

**Comment by Eyal-Be** [comment]
@armisael Do you know if this error has any real impact, or is it safe to ignore?

**Comment by armisael** [comment]
In our case we didn't notice any real impact, so our solution was indeed to ignore it, but I can't assume this is true for all cases.

Also, people over https://github.com/microsoft/vscode/issues/218001 had what looks like the same issue, and fixed it a couple of months ago.

**Comment by suren-atoyan** [comment]
@armisael @Eyal-Be could you please try to load the latest `monaco-editor` version via `loader` and see if the fix @armisael mentioned [here](https://github.com/suren-atoyan/monaco-react/issues/647#issuecomment-2374382758) helps? You can do something like [this](https://github.com/suren-atoyan/monaco-react/issues/565#issuecomment-1867468334)

**Comment by tsx-ell** [comment]
i'm experiencing the same error and in my case it is a problem indeed:
i have a nextjs react app, and a page with a several Editors and DiffEditors, which can be switched by sidebar tabs,
in case where i have 2+ DiffEditors and i switch between them a couple times – i get the mentioned error and the result looks like monaco is showing me correct text in the DiffEditor but is using a model from the previous tab' DiffEditor to highlight the diffs:
![image](https://github.com/user-attachments/assets/62e00c21-4030-4dfd-bc99-6f030f89b025)

**Comment by SundaramMaheshkumar** [comment]
Any update to this as the issue is still there when the `DiffEditor` is unmounted !?

**Comment by sankalpmukim** [comment]
https://github.com/microsoft/vscode/issues/218001

**Comment by sankalpmukim** [comment]
https://github.com/microsoft/vscode/pull/222197

**Comment by SitholeWB** [comment]
I managed to solve this error by setting two fields to `true`, as per screenshot below:

` 
 keepCurrentOriginalModel={true}
keepCurrentModifiedModel={true}
`

![Image](https://github.com/user-attachments/assets/2beb124d-d700-4bc9-9cd6-e85f59ad9d53)

**Comment by shreyasriram** [comment]
Hi @suren-atoyan, is there any update on this issue?

We're still encountering this error with monaco-editor@0.51.0 and 0.52.0, particularly in Firefox where it throws visibly and disrupts the UI.
We've temporarily worked around it by forcing the Monaco version to 0.50.0 using @monaco-editor/loader as suggested earlier by @armisael 

While this workaround works for now, we would prefer to upgrade and stay current. Do you have any timeline or ETA for an official fix?

Thanks for your help!

**Comment by suren-atoyan** [comment]
> Hi [@suren-atoyan](https://github.com/suren-atoyan), is there any update on this issue?
> 
> We're still encountering this error with monaco-editor@0.51.0 and 0.52.0, particularly in Firefox where it throws visibly and disrupts the UI. We've temporarily worked around it by forcing the Monaco version to 0.50.0 using @monaco-editor/loader as suggested earlier by [@armisael](https://github.com/armisael)
> 
> While this workaround works for now, we would prefer to upgrade and stay current. Do you have any timeline or ETA for an official fix?
> 
> Thanks for your help!

have you tried [this](https://github.com/suren-atoyan/monaco-react/issues/647#issuecomment-2897027817)?

**Comment by shreyasriram** [comment]
> > Hi [@suren-atoyan](https://github.com/suren-atoyan), is there any update on this issue?
> > We're still encountering this error with monaco-editor@0.51.0 and 0.52.0, particularly in Firefox where it throws visibly and disrupts the UI. We've temporarily worked around it by forcing the Monaco version to 0.50.0 using @monaco-editor/loader as suggested earlier by [@armisael](https://github.com/armisael)
> > While this workaround works for now, we would prefer to upgrade and stay current. Do you have any timeline or ETA for an official fix?
> > Thanks for your help!
> 
> have you tried [this](https://github.com/suren-atoyan/monaco-react/issues/647#issuecomment-2897027817)?

Yes it works. Thank you for your time

**Comment by volkandkaya** [comment]
> > Hi [@suren-atoyan](https://github.com/suren-atoyan), is there any update on this issue?
> > We're still encountering this error with monaco-editor@0.51.0 and 0.52.0, particularly in Firefox where it throws visibly and disrupts the UI. We've temporarily worked around it by forcing the Monaco version to 0.50.0 using @monaco-editor/loader as suggested earlier by [@armisael](https://github.com/armisael)
> > While this workaround works for now, we would prefer to upgrade and stay current. Do you have any timeline or ETA for an official fix?
> > Thanks for your help!
> 
> have you tried [this](https://github.com/suren-atoyan/monaco-react/issues/647#issuecomment-2897027817)?

Worked for me are you able to tag as solution and maybe add to the example in README?

**Comment by fengzi2016** [comment]
> I managed to solve this error by setting two fields to `true`, as per screenshot below:
> 
> ` keepCurrentOriginalModel={true} keepCurrentModifiedModel={true}`
> 
> ![Image](https://github.com/user-attachments/assets/2beb124d-d700-4bc9-9cd6-e85f59ad9d53)

When there are many editors, will this lead to memory leaks?
We should manage the textmodel by ourselves.

**Comment by fengzi2016** [comment]
您的邮件我已经收到，将会尽快给您回复，谢谢！
